#!/usr/bin/env bash

hostnamectl set-hostname x1

sudo dnf install vim-enhanced
sudo dnf install gnome-tweak-tool
sudo dnf install make
sudo dnf install ripgrep

# allow fractional scaling
gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"

if [ ! -f ~/.ssh/id_ed25519.pub ]
then
	ssh-keygen -t ed25519

	read -p "Manually add public ssh key to github, then press any key.."
else
	echo "ssh key detected, skipping creation"
fi

if ! [ -x "$(command -v cargo)" ]
then
	curl https://sh.rustup.rs -sSf | sh
	# update path after install for the installs below
	source ~/.profile

	rustup component add rustfmt
	rustup component add clippy
	rustup component add rls rust-analysis rust-src
else
	echo "detected rust installation, skipping install"
fi

if [[ ! -f ~/.cargo/config ]]
then
	mkdir -p ~/.cargo && ln ./.cargo/config ~/.cargo/config
else
	echo "detected .cargo directory, skpping cargo setup"
fi

if ! [ -x "$(command -v watchexec)" ]
then
	cargo install watchexec
else
	echo "detected watchexec installation, skipping install"
fi

if [[ ! -d ~/.vim ]]
then
	# dependency of coc-vim
	sudo dnf install nodejs

	git clone git@github.com:JoshMcguigan/dotvim.git
else
	echo "detected .vim directory, skpping vim setup"
fi

if ! [ -x "$(command -v pista)" ]
then
	cargo install pista
	echo "source ~/workspace/bootstrap/pista-bashrc" >> ~/.bashrc
else
	echo "detected pista installation, skipping install"
fi

if ! [ -x "$(command -v fzf)" ]
then
	sudo dnf install fzf
	echo "source ~/workspace/bootstrap/fzf-bashrc" >> ~/.bashrc
else
	echo "detected fzf installation, skipping install"
fi

if [[ ! -f ~/.gitconfig ]]
then
	ln ./.gitconfig ~/.gitconfig
else
	echo "detected .gitconfig, skpping gitconfig setup"
fi

if [[ ! -f ~/.gitignore_global ]]
then
	ln ./.gitignore_global ~/.gitignore_global
else
	echo "detected .gitignore_global, skpping gitignore setup"
fi

read -p "Manually configure caps lock key as ctrl using gnome tweak tool, then press any key.."
read -p "Manually configure display scaling, then press any key.."
read -p "Manually install uBlock Origin plugin for firefox, then press any key.."
read -p "Manually configure the terminal theme to light mode, then press any key.."
read -p "Manually configure the terminal to disable the bell, then press any key.."
read -p "Manually run :CocInstall coc-rls within vim (twice), then press any key.."
