#!/usr/bin/env bash

sudo dnf install vim-enhanced
sudo dnf install make
sudo dnf install ripgrep

# map caps lock to ctrl
gsettings set org.gnome.desktop.input-sources xkb-options ['ctrl:nocaps']

# set scaling
gsettings set org.gnome.desktop.interface text-scaling-factor 1.5

if [ ! -f ~/.ssh/id_ed25519.pub ]
then
	ssh-keygen -t ed25519

	read -p "Manually add public ssh key to github, then press any key.."
else
	echo "ssh key detected, skipping creation"
fi

if ! [ -x "$(command -v cargo)" ]
then
	curl https://sh.rustup.rs -sSf | sh
	# update path after install for the installs below
	source ~/.profile

	rustup component add rustfmt
	rustup component add clippy
	rustup component add rls rust-analysis rust-src

	# install rust analyzer and return to current directory
	git clone https://github.com/rust-analyzer/rust-analyzer ~/workspace/rust-analyzer/ && cd ~/workspace/rust-analyzer/ && cargo xtask install --server
	cd ~/workspace/bootstrap
else
	echo "detected rust installation, skipping install"
fi

if [[ ! -f ~/.cargo/config ]]
then
	mkdir -p ~/.cargo && ln ./.cargo/config ~/.cargo/config
else
	echo "detected .cargo directory, skpping cargo setup"
fi

if ! [ -x "$(command -v watchexec)" ]
then
	cargo install watchexec
else
	echo "detected watchexec installation, skipping install"
fi

if [[ ! -d ~/.vim ]]
then
	# dependency of coc-vim
	sudo dnf install nodejs

	git clone git@github.com:JoshMcguigan/dotvim.git ~/.vim
else
	echo "detected .vim directory, skpping vim setup"
fi

if ! [ -x "$(command -v pista)" ]
then
	cargo install pista
	echo "source ~/workspace/bootstrap/pista-bashrc" >> ~/.bashrc
else
	echo "detected pista installation, skipping install"
fi

if ! [ -x "$(command -v fzf)" ]
then
	sudo dnf install fzf
	echo "source ~/workspace/bootstrap/fzf-bashrc" >> ~/.bashrc
else
	echo "detected fzf installation, skipping install"
fi

if ! [ -x "$(command -v flake8)" ]
then
	pip3 install --user flake8
else
	echo "detected flake8 installation, skipping install"
fi

if [[ ! -f ~/.gitconfig ]]
then
	ln -s ./.gitconfig ~/.gitconfig
else
	echo "detected .gitconfig, skpping gitconfig setup"
fi

if [[ ! -f ~/.gitignore_global ]]
then
	ln -s ./.gitignore_global ~/.gitignore_global
else
	echo "detected .gitignore_global, skpping gitignore setup"
fi

read -p "Manually set hostname with 'hostnamectl set-hostname \$DESIRED_HOSTNAME', then press any key.."
read -p "Manually install uBlock Origin plugin for firefox, then press any key.."
read -p "Manually configure the terminal theme to light mode, then press any key.."
read -p "Manually configure the terminal to disable the bell, then press any key.."
read -p "Manually run :CocInstall coc-rls within vim (twice), then press any key.."
